version: "2"
services: 
  app: 
    container_name: fujitsu-app
    image: fujitsu-app 
    ports:
      - "5050:81"
    links:
      - api
  api: 
    container_name: fujitsu-api
    image: fujitsu-api 
    ports:
      - "57116:80"
    links:
      - fujitsu-db
  fujitsu-db:     
    container_name: fujitsu-db
    image: tutum/mongodb 
    ports:
      - "27017:27017"
      - "28017:28017"   
    environment:
      - AUTH=no