version: "2"
services: 
  app_dev: 
    image: fujitsudev-app 
    ports:
      - "4000:80"
    depends_on:
      - api_dev
  api_dev: 
    image: fujitsudev-api 
    ports:
      - "5000:80"
    depends_on:
      - fujitsudev-db
  fujitsudev-db:     
    image: tutum/mongodb 
    ports:
      - "27117:27017"
      - "28117:28017" 
    volumes:
      - /Users/tadriano/Documents/data/dev:/data/db  
    environment: 
      - AUTH=no
  app_hml: 
    image: fujitsuhml-app 
    ports:
      - "4100:80"
    depends_on:
      - api_hml
  api_hml: 
    image: fujitsuhml-api 
    ports:
      - "5100:80"
    depends_on:
      - fujitsuhml-db
  fujitsuhml-db:     
    image: tutum/mongodb 
    ports:
      - "27217:27017"
      - "28217:28017" 
    volumes:
      - /Users/tadriano/Documents/data/hml:/data/db  
    environment: 
      - AUTH=no
  app_prod: 
    image: fujitsuhml-app 
    ports:
      - "4200:80"
    links:
      - api_prod
  api_prod: 
    image: fujitsu-api 
    ports:
      - "5200:80"
    depends_on:
      - fujitsu-db
  fujitsu-db:     
    image: tutum/mongodb 
    ports:
      - "27317:27017"
      - "28317:28017" 
    volumes:
      - /Users/tadriano/Documents/data/prod:/data/db  
    environment: 
      - AUTH=no