version: "3"
services: 
  api_dev: 
    container_name: products-api
    image: tadrianonet/apiproducts
    ports:
      - "80:80"
    links:
      - products-db
  products-db:     
    container_name: products-db
    image: tutum/mongodb 
    ports:
      - "27017:27017"
      - "28017:28017"   
    environment:
      - AUTH=no