version: "2"
services:   
  api_dev: 
    container_name: fujitsudev-api
    image: fujitsudev-api 
    ports:
      - "5000:80"
    depends_on:
      - fujitsudev-db
  fujitsudev-db:     
    container_name: fujitsudev-db
    image: tutum/mongodb 
    ports:
      - "27117:27017"
      - "28117:28017" 
    volumes:
      - /Users/tadriano/Documents/data/dev:/data/db  
    environment: 
      - AUTH=no
  api_hml: 
    container_name: fujitsuhml-api
    image: fujitsuhml-api 
    ports:
      - "5100:80"
    depends_on:
      - fujitsuhml-db
  fujitsuhml-db:     
    container_name: fujitsuhml-db
    image: tutum/mongodb 
    ports:
      - "27217:27017"
      - "28217:28017" 
    volumes:
      - /Users/tadriano/Documents/data/hml:/data/db  
    environment: 
      - AUTH=no
  api_prod: 
    container_name: fujitsu-api
    image: fujitsu-api 
    ports:
      - "5200:80"
    depends_on:
      - fujitsu-db
  fujitsu-db:     
    container_name: fujitsu-db
    image: tutum/mongodb 
    ports:
      - "27317:27017"
      - "28317:28017" 
    volumes:
      - /Users/tadriano/Documents/data/prod:/data/db  
    environment: 
      - AUTH=no     